platform :ios, ‘7.0’

target ‘MyTemplateProject’ do

pod 'AFNetworking', '~> 3.1.0'

#pod 'ReactiveCocoa', '~> 2.5'

#pod 'BaiduMapKit' #百度地图SDK

pod 'ActionSheetPicker-3.0'

pod 'WebViewJavascriptBridge', '~> 5.0'

pod 'YYText'

pod 'XAspect'

pod 'RegexKitLite', '4.0'

pod 'CYLTabBarController'

pod 'Masonry'

pod 'CocoaLumberjack'

pod 'Aspects'

pod 'BlocksKit'

pod 'MJExtension'

pod 'SDWebImage'

pod 'IQKeyboardManager', '3.0.0'

pod 'MJRefresh'

pod 'SVProgressHUD'

pod 'MBProgressHUD'

pod 'YYCategories'

pod 'SDCycleScrollView'

pod 'AMapLocation' #定位SDK

pod 'FXBlurView'

end
